#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
    0xB93D94D1,
	0x5FB7330F,
	0x5FB73236,
	0x05E68E0F,
	0x05E692D4,
	0x5FB735B8,
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
